#ifndef PEONYQTENGRAMPAMENUPLUGIN_GLOBAL_H
#define PEONYQTENGRAMPAMENUPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEONYQTENGRAMPAMENUPLUGIN_LIBRARY)
#  define PEONYQTENGRAMPAMENUPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEONYQTENGRAMPAMENUPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEONYQTENGRAMPAMENUPLUGIN_GLOBAL_H
