#ifndef PEONYQTCREATELINK_GLOBAL_H
#define PEONYQTCREATELINK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEONYQTCREATELINK_LIBRARY)
#  define PEONYQTCREATELINKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEONYQTCREATELINKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEONYQTCREATELINK_GLOBAL_H
